"""Add user_clicks table

Revision ID: a20cdf89cc5e
Revises: 
Create Date: 2025-02-05 20:45:21.462372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a20cdf89cc5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generators', 'generator_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('generators', 'technology',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('generators', 'nameplate_capacity_mw',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('generators', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('plants', 'plant_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('plants', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('plants', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_plants_latitude'), 'plants', ['latitude'], unique=False)
    op.create_index(op.f('ix_plants_longitude'), 'plants', ['longitude'], unique=False)
    op.create_index(op.f('ix_plants_plant_code'), 'plants', ['plant_code'], unique=False)
    op.create_index(op.f('ix_plants_plant_name'), 'plants', ['plant_name'], unique=False)
    op.alter_column('utilities', 'utility_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_utilities_utility_id'), 'utilities', ['utility_id'], unique=False)
    op.create_index(op.f('ix_utilities_utility_name'), 'utilities', ['utility_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utilities_utility_name'), table_name='utilities')
    op.drop_index(op.f('ix_utilities_utility_id'), table_name='utilities')
    op.alter_column('utilities', 'utility_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_plants_plant_name'), table_name='plants')
    op.drop_index(op.f('ix_plants_plant_code'), table_name='plants')
    op.drop_index(op.f('ix_plants_longitude'), table_name='plants')
    op.drop_index(op.f('ix_plants_latitude'), table_name='plants')
    op.alter_column('plants', 'longitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('plants', 'latitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('plants', 'plant_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('generators', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('generators', 'nameplate_capacity_mw',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('generators', 'technology',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('generators', 'generator_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
